name: Publish

# https://github.com/marketplace/actions/upload-files-to-a-github-release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
          cache: 'maven'
      - name: Maven build
        run: mvn --batch-mode clean install
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/ldap-server.jar
          tag: ${{ github.ref }}
          overwrite: true
